package org.rsmod.content.bosses.doom

internal data class DoomDelve(
    val level: Int,
    val hitpoints: Int,
    val attackSpeed: Int,
    val standardMaxHit: Int,
    val basicProjTravel: Int,
    val basicProjMeleeStyle: Boolean,
    val secondaryProjCount: Int,
    val rockShrapnelQuantity: IntRange,
    val beamDamage: Int,
    val punishDelay: Int,
    val shockwaveSlams: Int,
    val shieldCrawls: Boolean,
    val larvaPrayer: LarvaPrayer,
    val acid: AcidSpread?,
    val shieldLarvaRate: IntRange?,
    val larvaSpawnCount: Int = 1,
    val burrowRocks: IntRange = 25..29,
    val trampleDamage: Int = 10,
    val carSlams: Int = 0,
    val secondaryProjTravel: Int = 90,
    val rushSpeed: Int = 4,
    val doubleRockThrow: Boolean = false,
    val giantLarva: Boolean = false,
    val burrowCentreRock: Boolean = true,
) {
    val freshArena: Boolean
        get() = level == 6

    val hasShield: Boolean
        get() = shieldLarvaRate != null

    val hasBurrow: Boolean
        get() = level >= 5

    companion object {
        private val NAMED: List<DoomDelve> =
            listOf(
                DoomDelve(
                    level = 1,
                    hitpoints = 525,
                    attackSpeed = 6,
                    standardMaxHit = 47,
                    basicProjTravel = 150,
                    basicProjMeleeStyle = false,
                    secondaryProjCount = 1,
                    rockShrapnelQuantity = 7..8,
                    beamDamage = 60,
                    punishDelay = 7,
                    shockwaveSlams = 1,
                    shieldCrawls = true,
                    larvaPrayer = LarvaPrayer.MeleeOrNone,
                    acid = null,
                    shieldLarvaRate = null,
                ),
                DoomDelve(
                    level = 2,
                    hitpoints = 550,
                    attackSpeed = 6,
                    standardMaxHit = 50,
                    basicProjTravel = 150,
                    basicProjMeleeStyle = true,
                    secondaryProjCount = 2,
                    rockShrapnelQuantity = 10..12,
                    beamDamage = 60,
                    punishDelay = 7,
                    shockwaveSlams = 1,
                    shieldCrawls = false,
                    larvaPrayer = LarvaPrayer.MeleeOrNone,
                    acid = null,
                    shieldLarvaRate = null,
                ),
                DoomDelve(
                    level = 3,
                    hitpoints = 575,
                    attackSpeed = 5,
                    standardMaxHit = 50,
                    basicProjTravel = 120,
                    basicProjMeleeStyle = true,
                    secondaryProjCount = 2,
                    rockShrapnelQuantity = 12..15,
                    beamDamage = 60,
                    punishDelay = 6,
                    shockwaveSlams = 2,
                    shieldCrawls = false,
                    larvaPrayer = LarvaPrayer.RandomSingle,
                    acid = AcidSpread(maxBleeds = 2),
                    shieldLarvaRate = 7..9,
                ),
                DoomDelve(
                    level = 4,
                    hitpoints = 600,
                    attackSpeed = 5,
                    standardMaxHit = 53,
                    basicProjTravel = 120,
                    basicProjMeleeStyle = true,
                    secondaryProjCount = 3,
                    rockShrapnelQuantity = 15..18,
                    beamDamage = 80,
                    punishDelay = 6,
                    shockwaveSlams = 2,
                    shieldCrawls = false,
                    larvaPrayer = LarvaPrayer.Coloured,
                    acid = AcidSpread(maxBleeds = 3, scatterPercent = 40, scatterAlong = 1..9, scatterLateral = 4),
                    shieldLarvaRate = 7..9,
                ),
                DoomDelve(
                    level = 5,
                    hitpoints = 625,
                    attackSpeed = 5,
                    standardMaxHit = 53,
                    basicProjTravel = 90,
                    basicProjMeleeStyle = true,
                    secondaryProjCount = 3,
                    rockShrapnelQuantity = 17..20,
                    beamDamage = 80,
                    punishDelay = 6,
                    shockwaveSlams = 3,
                    shieldCrawls = false,
                    larvaPrayer = LarvaPrayer.Coloured,
                    acid = AcidSpread(maxBleeds = 3, scatterPercent = 40, scatterAlong = 1..9, scatterLateral = 4),
                    shieldLarvaRate = 5..7,
                    larvaSpawnCount = 2,
                ),
                DoomDelve(
                    level = 6,
                    hitpoints = 650,
                    attackSpeed = 5,
                    standardMaxHit = 57,
                    basicProjTravel = 90,
                    basicProjMeleeStyle = true,
                    secondaryProjCount = 3,
                    rockShrapnelQuantity = 18..21,
                    beamDamage = 99,
                    punishDelay = 6,
                    shockwaveSlams = 3,
                    shieldCrawls = false,
                    larvaPrayer = LarvaPrayer.Coloured,
                    acid = AcidSpread(maxBleeds = 3, scatterPercent = 40, scatterAlong = 1..9, scatterLateral = 4),
                    shieldLarvaRate = 5..7,
                    larvaSpawnCount = 2,
                    burrowRocks = 21..23,
                    trampleDamage = 20,
                    carSlams = 3,
                ),
                DoomDelve(
                    level = 7,
                    hitpoints = 650,
                    attackSpeed = 4,
                    standardMaxHit = 65,
                    basicProjTravel = 90,
                    basicProjMeleeStyle = true,
                    secondaryProjCount = 3,
                    rockShrapnelQuantity = 20..24,
                    beamDamage = 99,
                    punishDelay = 5,
                    shockwaveSlams = 4,
                    shieldCrawls = false,
                    larvaPrayer = LarvaPrayer.Coloured,
                    acid = AcidSpread(maxBleeds = 3, scatterPercent = 40, scatterAlong = 1..9, scatterLateral = 4),
                    shieldLarvaRate = 4..6,
                    larvaSpawnCount = 2,
                    burrowRocks = 22..23,
                    trampleDamage = 30,
                    carSlams = 3,
                    secondaryProjTravel = 30,
                    rushSpeed = 6,
                ),
                DoomDelve(
                    level = 8,
                    hitpoints = 675,
                    attackSpeed = 4,
                    standardMaxHit = 65,
                    basicProjTravel = 90,
                    basicProjMeleeStyle = true,
                    secondaryProjCount = 3,
                    rockShrapnelQuantity = 16..26,
                    beamDamage = 99,
                    punishDelay = 5,
                    shockwaveSlams = 5,
                    shieldCrawls = false,
                    larvaPrayer = LarvaPrayer.Coloured,
                    acid = AcidSpread(maxBleeds = 4, scatterPercent = 40, scatterAlong = 1..12, scatterLateral = 6),
                    shieldLarvaRate = 4..6,
                    larvaSpawnCount = 1,
                    burrowRocks = 15..16,
                    trampleDamage = 40,
                    carSlams = 3,
                    secondaryProjTravel = 30,
                    rushSpeed = 8,
                    doubleRockThrow = true,
                    giantLarva = true,
                    burrowCentreRock = false,
                ),
            )

        const val DEEP_LEVEL = 9
        private const val DEEP_HITPOINTS = 625

        val DEEPEST: Int = NAMED.last().level

        val LEVELS: List<DoomDelve> = NAMED + NAMED.last().copy(level = DEEP_LEVEL, hitpoints = DEEP_HITPOINTS)

        fun of(level: Int): DoomDelve = LEVELS.first { it.level == minOf(level, DEEP_LEVEL) }
    }
}
