plugins {
    id("base-conventions")
    id("integration-test-suite")
}

kotlin {
    explicitApi()
}

dependencies {
    api(libs.guice)
    api(projects.api.cache)
    api(projects.api.config)
    api(projects.api.controller)
    api(projects.api.npc)
    api(projects.api.player)
    api(projects.api.playerOutput)
    api(projects.api.random)
    api(projects.api.repo)
    api(projects.api.route)
    api(projects.api.script)
    api(projects.api.testing.testAssertions)
    api(projects.api.testing.testCapture)
    api(projects.api.testing.testFactory)
    api(projects.api.testing.testParams)
    api(projects.api.testing.testRandom)
    api(projects.api.utils.utilsVars)
    api(projects.engine.events)
    api(projects.engine.game)
    api(projects.engine.map)
    api(projects.engine.objtx)
    api(projects.engine.plugin)
    api(projects.engine.routefinder)
    implementation(libs.bundles.logging)
    implementation(libs.clikt)
    implementation(libs.fastutil)
    implementation(libs.guice)
    implementation(libs.jupiter.api)
    implementation(libs.kotlin.coroutines.core)
    implementation(projects.api.account)
    implementation(projects.api.cache)
    implementation(projects.api.db)
    implementation(projects.api.gameProcess)
    implementation(projects.api.invPlugin)
    implementation(projects.api.market)
    implementation(projects.api.net)
    implementation(projects.api.realm)
    implementation(projects.api.registry)
    implementation(projects.api.serverConfig)
    implementation(projects.api.stats.levelmod)
    implementation(projects.api.stats.xpmod)
    implementation(projects.api.utils.utilsLogging)
    implementation(projects.engine.annotations)
    implementation(projects.engine.module)
    // The game's Guice module graph (`GameModule`) and, through `server:shared`, every api and
    // content module, so a test boots the same classpath as the server.
    implementation(projects.server.app)
    implementation(projects.server.shared)
    integrationImplementation(libs.kotlin.coroutines.core)
    integrationImplementation(projects.api.areaChecker)
    integrationImplementation(projects.api.db)
    integrationImplementation(projects.api.serverConfig)
    integrationImplementation(projects.api.shops)
}
